"""simplify refresh tokens model for test

Revision ID: 0ec6c4bf2efd
Revises: 24759855fbc5
Create Date: 2025-05-12 19:03:54.259174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec6c4bf2efd'
down_revision: Union[str, None] = '24759855fbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_sessions', 'user_agent')
    op.drop_column('refresh_sessions', 'ip')
    op.drop_column('refresh_sessions', 'fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_sessions', sa.Column('fingerprint', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('refresh_sessions', sa.Column('ip', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('refresh_sessions', sa.Column('user_agent', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
