"""Add Categories, Genres, Authors and relationships to Books

Revision ID: 2c323e15a4f7
Revises: 78f0eb2682b7
Create Date: 2025-05-06 21:29:06.114424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c323e15a4f7'
down_revision: Union[str, None] = '78f0eb2682b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_categories',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'genres', ['genre_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.alter_column('books', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'genre_id')
    op.drop_table('books_categories')
    op.drop_table('genres')
    op.drop_table('categories')
    op.drop_table('authors')
    # ### end Alembic commands ###
